### ISSUE TITLE
Remove old files

### ISSUE THREAD

**Issue by sledzik1984** [RomainGehrig/PDFCollate#6]
I know that this is on the todo list :) 

Pdfcollate made one of my servers die for few hours because of full disk (full of source PDF's that was collated) ;)

**Comment by RomainGehrig** [comment]
Hi ! Thanks for your interest, I went ahead and implemented the feature. My server thanks you too ;)

PDFCollate should now delete the old files by default and the feature can be disabled by setting the environment variable `DELETE_OLD_FILES` to `false`.

A new docker image with the feature is available (now supporting ARM/ARM64) and I pushed a new version (0.1.4) on PyPI too.
